imports:
    - { resource: voter.yml }
    - { resource: listener.yml }

services:
    core.manager.serializer_groups:
        class: CoreBundle\Service\SerializerGroupsManager
        arguments:
            - "@request_stack"

    core.paginator:
        class: CoreBundle\Service\Paginator
