imports:
    - { resource: voter.yml }
    - { resource: listener.yml }
    - { resource: filter.yml }

services:
    core.manager.serializer_groups:
        class: CoreBundle\Service\SerializerGroupsManager
        arguments:
            - "@request_stack"

    core.paginator:
        class: CoreBundle\Service\Paginator

    core.custom_parser:
        class: CoreBundle\Parser\Parser
        public: false
        arguments:
            - '@nelmio_api_doc.parser.form_type_parser'
            - '@nelmio_api_doc.parser.validation_parser'
            - '@form.factory'
            - '@nelmio_api_doc.doc_comment_extractor'
        tags:
            - { name: nelmio_api_doc.extractor.parser, priority: 2 }
