UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username

    properties:
        username:
            - Type: string
        email:
            - Type: string
        plainPassword:
            - Type: string
