imports:
    - { resource: voter.yml }
    - { resource: repository.yml }
    - { resource: filter.yml }

services:
    user.command.create_client:
        class: UserBundle\Command\CreateClientCommand
        tags:
            - { name: console.command }
        arguments:
            - '@fos_oauth_server.client_manager.default'

    user.mailer:
        class: UserBundle\Mailer\Mailer
        arguments:
            - '@mailer'
            - '@twig'
            - { base_url_confirmation: '%base_url_confirmation%', base_url_reset: '%base_url_reset%' }

    user.user_listener:
        class: UserBundle\EventListener\UserListener
        arguments:
            - '@service_container'
        tags:
            - { name: doctrine.orm.entity_listener, entity: UserBundle\Entity\User, event: prePersist, method: prePersistHandler }

    user.user_edit_admin_type:
        class: UserBundle\Form\UserEditAdminType
        arguments:
            - "@security.token_storage"
        tags:
            - { name: form.type }
