imports:
    - { resource: voter.yml }

services:
    user.command.create_client:
        class: UserBundle\Command\CreateClientCommand
        tags:
            - { name: console.command }
        #arguments: ['@fos_oauth_server.client_manager.default']
        # sorry https://github.com/doctrine/DoctrineBundle/issues/300
        arguments: ['@service_container']

    user.mailer:
        class: UserBundle\Mailer\Mailer
        public: false
        arguments:
            - '@mailer'
            - '@twig'
            - { base_url_confirmation: '%base_url_confirmation%' }

    user.user_listener:
        class: UserBundle\EventListener\UserListener
        arguments:
            - '@user.mailer'
            - '@fos_user.util.token_generator'
        tags:
            - { name: doctrine.orm.entity_listener, entity: UserBundle\Entity\User, event: prePersist, method: prePersistHandler }
