<?php

namespace CoreBundle\Repository;

/**
 * LogRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
