CoreBundle\Entity\LogRequest:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [default]
        route:
            expose: true
            groups: [default]
        method:
            expose: true
            groups: [default]
        path:
            expose: true
            groups: [default]
        query:
            expose: true
            groups: [default]
        content:
            expose: true
            groups: [detail-logrequest]
        response:
            expose: true
            groups: [detail-logrequest]
        status:
            expose: true
            groups: [default]
        ip:
            expose: true
            groups: [default]
        createdAt:
            expose: true
            groups: [default]

    relations:
        -
            rel: self
            href:
                route: api_get_log_request
                parameters:
                    log_request_id: expr(object.getId())
            exclusion:
                groups: [default]

        -
            rel: user
            embedded:
                content: expr(object.getUser())
            exclusion:
                groups: [default]
